language: c

sudo: false

cache: ccache

addons:
  apt:
    packages:
    - gcc-multilib
    - libc6-i386
    - libc6-dev-i386
    - binutils-mingw-w64-i686
    - gcc-mingw-w64-i686
    - g++-mingw-w64-i686
    - binutils-mingw-w64-x86-64
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
    - wine

script:
- cd Source
- make -f Makefile.unix
